name: Convert Issues to Pull Requests

on:
  issues:
    types: [opened]

jobs:
  convert-issue-to-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.SUGGESTIONS_PULLS }}
        commit-message: 'Add new suggestion'
        committer: 'GitHub Actions <actions@github.com>'
        author: 'GitHub Actions <actions@github.com>'
        title: 'New suggestion: ${{ github.event.issue.title }}'
        body: ${{ github.event.issue.body }}
        branch: suggestion-branch-${{ github.event.issue.number }}
        base: main

    - name: Close Issue
      if: steps.create_pr.outputs.pull-request-url
      uses: peter-evans/close-issue@v2
      with:
        issue-number: ${{ github.event.issue.number }}
        comment: 'This issue has been converted to a pull request: ${{ steps.create_pr.outputs.pull-request-url }}'
        token: ${{ secrets.SUGGESTIONS_PULLS }}
